################################
# --- Site identity --- #
################################

title: Teddy Maginn
author: Teddy Maginn
description: Urban policy & analytics

################################
# --- Navigation bar --- #
################################

navbar-links:
  About: "/"
  Projects: "projects"
  Blog: "https://substack.com/@teddymaginn"
  Research: "publications"
  CV: "assets/CV.pdf"

################################
# --- Branding --- #
################################

# avatar: "assets/img/southbend1920.png"
# round-avatar: false

################################
# --- Social links (footer) --- #
################################

social-network-links:
  email: "tjmaginn6@gmail.com"
  linkedin: teddy-maginn
  # github: tjmaginn

################################
# --- General behavior --- #
################################

title-on-all-pages: true
post_search: true
edit_page_button: true

################################
# --- Appearance --- #
################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
footer-col: "#EAEAEA"
footer-text-col: "#777777"


site-css:
  - "/assets/css/custom.css"

################################
# --- Jekyll core settings --- #
################################

markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 5
timezone: America/New_York

plugins:
  - jekyll-paginate
  - jekyll-sitemap
